version: "3.9"
services:
  # nginx container
  nginx:
    image: nginx
    container_name: nginx-${TAG}
    build:
      context: ./docker/nginx
      dockerfile: nginx.dockerfile
    platform: ${PLATFORM}
    restart: always
    networks:
      - my-network
    volumes:
      - ./docker/nginx/log:/var/log/nginx
      - $SRC:/var/www/html
    ports:
      - "${NGINX_HTTP_PORT}:80"
      - "${NGINX_HTTPS_PORT}:443"
    links:
      - phpfpm
    depends_on:
      redis:
        condition: service_healthy
      mysql:
        condition: service_healthy
  # php-fpm container
  phpfpm:
    image: phpfpm
    container_name: phpfpm-${TAG}
    build:
      context: ./docker/phpfpm
      dockerfile: phpfpm.dockerfile
      args:
        PHP_TAG: ${PHP_TAG}
        TZ: ${TZ}
    platform: ${PLATFORM}
    restart: always
    networks:
      - my-network
    volumes:
      - $SRC:/var/www/html
    ports:
      - "${PHP_FPM_PORT}:9000"
    depends_on:
      redis:
        condition: service_healthy
      mysql:
        condition: service_healthy
  # MySQL container
  mysql:
    image: mysql
    container_name: mysql-${TAG}
    build:
      context: ./docker/mysql
      dockerfile: mysql.dockerfile
    platform: ${PLATFORM}
    restart: always
    networks:
      - my-network
    env_file:
      - ./docker/mysql/mysql.env
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${MYSQL_ROOT_PASSWORD}"]
      timeout: 20s
      retries: 10
  # Redis container
  redis:
    image: redis
    container_name: redis-${TAG}
    build:
      context: ./docker/redis
      dockerfile: redis.dockerfile
    platform: ${PLATFORM}
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ./docker/redis/data:/data
    networks:
      - my-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 30s
      retries: 50
# Define networks
networks:
  my-network:
    driver: bridge
