version: "3.9"
services:
  # nginx container
  nginx:
    image: nginx
    container_name: nginx-${TAG}
    build:
      context: ./nginx
      dockerfile: nginx.dockerfile
    platform: linux/arm64/v8
    restart: always
    networks:
      - my-network
    volumes:
      - ./nginx/log:/var/log/nginx
      - ./app:/var/www/html
    ports:
      - "${NGINX_HTTP_PORT}:80"
      - "${NGINX_HTTPS_PORT}:443"
    links:
      - phpfpm
    depends_on:
      redis:
        condition: service_healthy
      mysql:
        condition: service_healthy
  # php-fpm container
  phpfpm:
    image: phpfpm
    container_name: phpfpm-${TAG}
    build:
      context: ./phpfpm
      dockerfile: phpfpm.dockerfile
      args:
        PHP_TAG: ${PHP_TAG}
    platform: linux/arm64/v8
    restart: always
    networks:
      - my-network
    volumes:
      - ./app:/var/www/html
    ports:
      - "${PHP_FPM_PORT}:9000"
    depends_on:
      redis:
        condition: service_healthy
      mysql:
        condition: service_healthy
  # MySQL container
  mysql:
    image: mysql
    container_name: mysql-${TAG}
    build:
      context: ./mysql
      dockerfile: mysql.dockerfile
    platform: linux/arm64/v8
    restart: always
    networks:
      - my-network
    env_file:
      - ./mysql/mysql.env
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${MYSQL_ROOT_PASSWORD}"]
      timeout: 20s
      retries: 10
  # Redis container
  redis:
    image: redis
    container_name: redis-${TAG}
    build:
      context: ./redis
      dockerfile: redis.dockerfile
    platform: linux/arm64/v8
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ./redis/data:/data
    networks:
      - my-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 30s
      retries: 50
  # phpMyAdmin container
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin-${TAG}
    build:
      context: ./phpMyAdmin
      dockerfile: phpMyAdmin.dockerfile
    platform: linux/arm64/v8
    restart: always
    networks:
      - my-network
    ports:
      - "${PHPMYADMIN_HTTP_PORT}:80"
    env_file:
      - ./phpMyAdmin/phpMyAdmin.env
    links:
      - mysql:mysql
# Define networks
networks:
  my-network:
    driver: bridge
